### ISSUE TITLE
Tauri bundle for desktop apps

### ISSUE THREAD

**Issue by depler** [6c65726f79/Transmissionic#111]
Hey, did you consider using tauri for desktop apps instead of electron? According to internet, it will reduce binary size just to several megabytes due to using system webview instead of chromium bundle. More info: https://www.smashingmagazine.com/2020/07/tiny-desktop-apps-tauri-vuejs/

**Comment by 6c65726f79** [comment]
Hey, very interesting suggestion, I didn't know this project!

It would be really nice to be able to reduce the binary size on desktops, but it seems that Tauri doesn't have as much features as Electron, probably because the project is still in alpha version. For example it's not possible to open a folder in the system file explorer.

So for now this is not a perfect replacement, but it's definitely promising and I will follow the evolution of this project. Thank you for letting me know about it.

**Comment by 6c65726f79** [comment]
After some research, I've come to the conclusion that Tauri will not be suitable for bundling an app built with Ionic, because of the incompatibility between Ionic and Tauri's WebView. It can be solved by installing Microsoft's [WebView2](https://developer.microsoft.com/en-us/microsoft-edge/webview2/), but we end up with the same problem of binary size.
So I'm closing the issue for now, but i'll reopen it if there's anything new.
