### ISSUE TITLE
Another question about compactMode

### ISSUE THREAD

**Issue by tsimmons** [6c65726f79/Transmissionic#1232]
**Describe the bug**
This might just be my inability to find the option, but how do you toggle "Compact mode"? I have some browsers that the view is "compact" and others that are not. For the life of me I cannot figure out how to toggle it through any of the settings dialogs. Surely I am missing something?

**Comment by tsimmons** [comment]
I've figured out how to change it (use browser's "Inspect" tool, look at "Storage" -> "Local storage" and add the following key)

    CapacitorStorage.compactMode = true

But I guess my question still stands, is there an option to toggle this in the GUI as this is not really possible with mobile devices? Thanks!

**Comment by cengbrecht** [comment]
> But I guess my question still stands, is there an option to toggle this in the GUI as this is not really possible with mobile devices? Thanks!

To my knowledge its been in the settings menu the whole time? 
This is the settings on the desktop, I have not checked the phone. Since they are the same interface, I presume they would be the same?

![image](https://user-images.githubusercontent.com/1149435/215291175-e260956c-c96e-48e8-876b-18a1da5fd94b.png)

**Comment by tsimmons** [comment]
Oh for Pete's sake, yep, I just missed that in the settings. I think my settings panel was scrolled down and I didn't notice because those options were scrolled up out of view. Not a bug, user error on me. Thank you!
