### ISSUE TITLE
Bookmarklet feature

### ISSUE THREAD

**Issue by aptonline** [6c65726f79/Transmissionic#131]
I know this is probably out of the scope of Transmissionic but it would be good to be able to send torrents/magnets directly to transmission via a bookmarklet from any webpage.

My searching for this elsewhere turned up solutions from 10 years ago!

Thoughts?

**Comment by 6c65726f79** [comment]
This sounds very interesting, I would love to implement this feature, but I'm not sure if it's possible to do this from a Web UI only. 

Usually, bookmarklet are used to send the current page URL to an external service, here I need to search in the page if there are magnets or hashs, which can lead in false positives. But it may be possible with some tricks, I will try this soon.

Alternatively, you could try to build the Electron client for Mac OS, this can be done with a few command lines by following the [Build](https://github.com/6c65726f79/Transmissionic#electron-1) steps and running `npm run-script electron:build-mac`.
This will allow you to open magnets and torrent files directly in Transmissionic.

**Comment by aptonline** [comment]
That’s great, happy to test if you find a way.

**Comment by aptonline** [comment]
Not sure if this is any use but javascript seems an option: https://www.hongkiat.com/blog/make-bookmarklet-with-javascript/

**Comment by 6c65726f79** [comment]
All bookmarklets use javascript, but there are some limitations.
Bookmarklets work fine when there is only one element in the page, for example on YouTube there's only one video player in the page, same for streaming sites. But for torrent sites, some sites display multiples magnet links on the same page, so the script can't tell which one to take. 
That's why it's more efficient to do it with an extension which allows to use the context menu.
The bookmarklet method will not work on all websites, by I will still try to add it as a bonus feature.

**Comment by 6c65726f79** [comment]
Feature added in [v1.1.7](https://github.com/6c65726f79/Transmissionic/releases/tag/v1.1.7), you can find more information in the [Bookmarlet](https://github.com/6c65726f79/Transmissionic#bookmarlet) section. I hope this will meet your needs.

**Comment by aptonline** [comment]
This works perfectly from my initial use (will test further), 2 days turn around from initial suggestion to implementation is pretty good. Well done :)

**Comment by 6c65726f79** [comment]
You can now use the bookmarklet to import torrent file links in [v1.1.8](https://github.com/6c65726f79/Transmissionic/releases/tag/v1.1.8), this should work with most sites, but not on private trackers.
