### ISSUE TITLE
Cannot add external server to WebUI

### ISSUE THREAD

**Issue by depler** [6c65726f79/Transmissionic#137]
Tried to add external server (not localhost) to webui and got this error:
![image](https://user-images.githubusercontent.com/13541699/114863171-13870c80-9df8-11eb-9398-ff0fa4ad72a3.png)

Is it possible to solve somehow?

**Comment by 6c65726f79** [comment]
It's not possible by default, this is due to the fact that Transmission requires that the requests come from the same host. There is two ways to solve this :
- Recommanded: You can set-up a reverse proxy to access Transmission with CORS allowed ([More info](https://medium.com/@dtkatz/3-ways-to-fix-the-cors-error-and-how-access-control-allow-origin-works-d97d55946d9))
- Not recommanded: You can disable web security in your browser like described in the [Development](https://github.com/6c65726f79/Transmissionic#development) section, but you should not browse the web without web security!

**Comment by depler** [comment]
Not a big problem anyway
