### ISSUE TITLE
save credentials in webui

### ISSUE THREAD

**Issue by jiangjiangflies** [6c65726f79/Transmissionic#616]
How to save authentication credentials in webui？I don't want to enter credentials in the pop-up window of my Safari each time. The authentication details are greyed out so I can't save them in Safari. #126 
I tried to inspect the inputs and remove the "disabled" attribute, but itdidn't work. I don't know where went wrong.
Can you provide an option to save credentials rather than disabling them by default?
It is really annoying to enter credentials by hand from time to time since Safari never remember them. So I really need this feature.
Thank you so much.

**Comment by 6c65726f79** [comment]
Unfortunately it's not possible, you need to be authenticated to load the Web UI, the problem comes from Transmission.
One solution would be to test with Firefox, I think it can remember credentials for HTTP authentication.
Otherwise, I am currently working on an application that is placed between Transmission and the Web UI to improve the functionality of the Web UI, including remembering credentials. But don't expect to see it released soon, there is still a lot of work to do.

**Comment by jiangjiangflies** [comment]
Thanks! Looking forward to it!

**Comment by 6c65726f79** [comment]
You can finally save credentials in the web ui with [v1.7.0](https://github.com/6c65726f79/Transmissionic/releases/tag/v1.7.0), sorry for the delay!
